[package]
name = "airdropsbot"
version = "0.1.0"
edition = "2024"

[lib]
name = "adb"

[dependencies]
reqwest = { version = "0.12.23", features = ["json","blocking","gzip"] }
serde_json = "1.0.145"
serde = "1.0.228"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
rusqlite = "0.37.0"