name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            target: 'aarch64-apple-darwin'
            artifact_name: 'airdropsbot'
            asset_name: 'airdropsbot-aarch64-apple-darwin'
          - platform: 'macos-latest'
            target: 'x86_64-apple-darwin'
            artifact_name: 'airdropsbot'
            asset_name: 'airdropsbot-x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            target: 'x86_64-unknown-linux-gnu'
            artifact_name: 'airdropsbot'
            asset_name: 'airdropsbot-x86_64-linux'
          - platform: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            artifact_name: 'airdropsbot.exe'
            asset_name: 'airdropsbot-x86_64-windows.exe'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './target'
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref_name }}
          overwrite: true